# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  deploy-job:
    machine:
      enabled: true
    steps:
      - add_ssh_keys: 
            fingerprints:
                - "6b:0e:cd:f2:32:16:75:48:06:98:a8:a9:36:5c:ae:03"
      - run: ssh -vT $USER@$SERVER_IP_ADDRESS "sh /var/www/deploy.sh"

workflows:
  version: 2
  website-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master